name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: fregante/setup-git-token@v1
        with:
          token: ${ GITHUB_TOKEN }
      - name: Release
        run: |
          git show -s --format=%s | grep '(release):' &> /dev/null
          if [ $? != 0 ]; then
            yarn
            yarn preversion
            echo -e "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
            yarn release
            echo -e "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > .npmrc
            yarn publish
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
